### ISSUE TITLE
What's next plan?

### ISSUE THREAD

**Issue by janckerchen** [unageanu/jiji2#385]
I love ruby and this project,  write algo in ruby is awesome,  feel free and have fun!

Is this project  still developing, what's the next plan?

**Comment by unageanu** [comment]
Thank you.
I  am developping python support  which enable to develop trading algorithm by python language with the following branch, but development has stopped because I got busy for a while.
https://github.com/unageanu/jiji2/tree/python_supports

I am also thinking about iOS support, but I am hesitant because sales are subtle...

**Comment by janckerchen** [comment]
What does it mean python  support?  only high level trading algorithm part  or rewrite whole project?
how to communicate between them?

**Comment by unageanu** [comment]
> "only high level trading algorithm part"

Yes. The goal is to be able to create algorithms with python, and to make Python's library (TensorFlow, pandas .. etc ..) available.

the following methods are considered.
- Start a new Python process and run the algorithm on it.
- Interact with the Jiji process via gRPC.

**Comment by janckerchen** [comment]
> to make Python's library (TensorFlow, pandas .. etc ..) available.

awesome idea~  thanks a lot  for your job.
